#include "p16F1786.inc"

; CONFIG1
; __config 0x3FE4
 __CONFIG _CONFIG1, _FOSC_INTOSC & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _CLKOUTEN_OFF & _IESO_ON & _FCMEN_ON
; CONFIG2
; __config 0x3FFF
 __CONFIG _CONFIG2, _WRT_OFF & _VCAPEN_OFF & _PLLEN_ON & _STVREN_ON & _BORV_LO & _LPBOR_OFF & _LVP_ON
    UDATA_SHR
       ORDER RES 1H
       LOOPCNT RES 1H
       LENGTH RES 1H
       STARTTIME RES 1H
RES_VECT  CODE    0x0000            ; processor reset vector 
    PAGESEL START
    GOTO    START                   ; go to beginning of program


MAIN_PROG CODE                      ; let linker place main program

isr CODE 0x40
    BANKSEL INTCON
    BTFSC INTCON,TMR0IF
    CALL LIGHT
    BCF INTCON,TMR0IF 
    BCF INTCON,INTF
    MOVLW H'04'
    MOVWF LENGTH
    RETFIE
    
LIGHT
    BCF STATUS,C
    BANKSEL TRISB
    LSLF TRISB,1;
    INCF TRISB,1
    BTFSS TRISB,5
    CALL CLEAR 
    BANKSEL STATUS
    BSF STATUS,C
    CLRF WREG
    ADDWF ORDER,0
    ADDWF LOOPCNT,0
    SUBWFB LENGTH,1
    BTFSS STATUS,C
    CALL CHANGE
    CALL CONSTANTS
    BANKSEL LATA;
    MOVWF LATA
    INCF ORDER,1
    RETURN
    
CHANGE 
    COMF LENGTH
    CLRF WREG
    ADDWF LENGTH,0
    RETURN
    
CLEAR 
    BANKSEL TRISB;????
    MOVLW b'11111101'
    MOVWF TRISB;
    CLRF ORDER
    INCF LOOPCNT
    BTFSC LOOPCNT,2
    CLRF LOOPCNT
    RETURN
    
CONSTANTS 
    BRW
    RETLW B'00000110'
    RETLW B'10110011'  
    RETLW B'10010111'
    RETLW B'11000110'
    RETLW B'11111011'
    
START
    
    BANKSEL OSCCON  ; CP
    MOVLW B'01010000';500kHZ
    MOVWF OSCCON
    
    BANKSEL OPTION_REG 
    MOVLW B'11000000' ;1:256
    MOVWF OPTION_REG
    BANKSEL ANSELA
    CLRF ANSELA
    
    BANKSEL TRISA
    CLRF TRISA
    BANKSEL ANSELB
    CLRF ANSELB
    
    BANKSEL PORTA
    MOVLW H'00'
    MOVWF PORTA
    BANKSEL LATB
    MOVLW H'00'
    MOVWF LATB
    BANKSEL TRISB
    MOVLW B'11111110'
    MOVWF TRISB
    MOVLW H'04'
    MOVWF ORDER
    MOVLW H'FF'
    MOVWF STARTTIME
    STARTLOOP
	MOVLW ORDER
	CALL CONSTANTS
	MOVWF LATA
	MOVLW B'11111110'
	MOVWF TRISB
	DECFSZ STARTTIME
	GOTO STARTLOOP
    MOVLW H'04'
    MOVWF LENGTH
    BANKSEL TRISB
    MOVLW B'11111110'
    MOVWF TRISB
    
    CLRF ORDER
    CLRF LOOPCNT
MAINLOOP
    NOP
    GOTO MAINLOOP                         ; loop forever
END