; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
include <p16f1786.inc>
org 0
INIT:
    BANKSEL PORTA
    CLRF PORTA
    BANKSEL LATA
    CLRF LATA
    BANKSEL ANSELA
    CLRF ANSELA
    BANKSEL TRISA
    CLRF TRISA
    MOVLW b'11111100'  
    MOVWF TRISA
    MOVLW b'100000'
    MOVWF LATA
MAIN:
    DECFSZ LATA 1
    GOTO MAIN
    MOVLW b'10000'
    MOVWF LATA
    MOVLW b'1111111'
    MOVWF TRISA
    GOTO DELAY
    
DELAY:
    DECFSZ LATA 1
    GOTO DELAY
    MOVLW b'11111100'  
    MOVWF TRISA
    MOVLW b'10000'
    MOVWF LATA
    GOTO MAIN
end