START:
    BANKSEL PORTA
    CLRF PORTA
    MOVLW H'FF'
    MOVWF PORTA
;    BANKSEL LATA
;    CLRF LATA
;    BANKSEL ANSELA
;    CLRF ANSELA
    BANKSEL TRISA
    CLRF TRISA
;    MOVLW B'00000000'
;    MOVWF TRISA
    
end
