org 0x0

#include "p16f1786.inc"

; CONFIG1
; __config 0xFFFF
 __CONFIG _CONFIG1, _FOSC_ECH & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _CLKOUTEN_OFF & _IESO_ON & _FCMEN_ON
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _WRT_OFF & _VCAPEN_OFF & _PLLEN_ON & _STVREN_ON & _BORV_LO & _LPBOR_OFF & _LVP_ON
 
	UDATA_SHR
DELAYVAR1 RES 1H
 
RES_VECT  CODE    0x0000 
	  PAGESEL MAIN
	  GOTO    INIT 
MAIN_PROG CODE 

INIT:
    BANKSEL ANSELA
    CLRF ANSELA
    BANKSEL OSCCON
    BCF OSCCON,0
    BSF OSCCON,1
    BCF CONFIG1
    BANKSEL TRISA
    CLRF TRISA 
    MOVLW H'FF'
    MOVWF DELAYVAR1
    BANKSEL LATA
    CLRF LATA
    MOVLW H'ff'
    MOVWF LATA
    GOTO MAIN
    
MAIN:
    nop
    nop
    nop
    nop
    DECFSZ DELAYVAR1,1
    GOTO MAIN
    MOVLW H'FF'
    MOVWF DELAYVAR1
    MOVLW H'00'
    MOVWF LATA
    GOTO DELAY
    
DELAY:
    nop
    nop
    nop
    nop
    DECFSZ DELAYVAR1,1
    GOTO DELAY
    MOVLW H'ff'  
    MOVWF LATA
    MOVLW H'FF'
    MOVWF DELAYVAR1
    GOTO MAIN
end