#include "p16F1786.inc"

; CONFIG1
; __config 0x3FE4
 __CONFIG _CONFIG1, _FOSC_INTOSC & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _CLKOUTEN_OFF & _IESO_ON & _FCMEN_ON
; CONFIG2
; __config 0x3FFF
 __CONFIG _CONFIG2, _WRT_OFF & _VCAPEN_OFF & _PLLEN_ON & _STVREN_ON & _BORV_LO & _LPBOR_OFF & _LVP_ON

RES_VECT  CODE    0x0000            ; processor reset vector 
    PAGESEL START
    GOTO    START                   ; go to beginning of program


MAIN_PROG CODE                      ; let linker place main program

COUNT EQU 70H
 
ISR CODE 0x40
    BANKSEL INTCON
    BTFSC INTCON,TMR0IF
    call LIGHT1
    BCF INTCON,TMR0IF ;?????
    CLRF W
    BANKSEL INTCON
    BTFSC INTCON,INTF
    CALL LIGHT2
    BCF INTCON,INTF ;?????
    BANKSEL IOCBF
    BTFSC IOCBF,2
    CALL LIGHT3
    BANKSEL IOCBF
    BCF IOCBF,2
    RETFIE
LIGHT1:
    BANKSEL IOCBF
    BSF IOCBF,2
    MOVLW B'000000001'
    BANKSEL LATA
    XORWF LATA,1    
    RETURN
LIGHT2:
    BANKSEL LATA
    MOVLW B'0000001' ;1:256
    XORWF LATA,1
    RETURN
LIGHT3:
    BANKSEL LATA
    MOVLW B'00100000'
    XORWF LATA,1
    RETURN
    
    
START
    
    BANKSEL OSCCON  ; CP
    MOVLW B'01010000';500kHZ
    MOVWF OSCCON
    BANKSEL OPTION_REG 
    MOVLW B'11000111' ;1:256
    MOVWF OPTION_REG
    BANKSEL ANSELA
    CLRF ANSELA   
    BANKSEL TRISA
    CLRF TRISA 
    BANKSEL PORTA
    MOVLW H'00'
    MOVWF PORTA
    BANKSEL INTCON
    MOVLW B'11111000'
    MOVWF INTCON
    BANKSEL TRISB
    BSF TRISB,0 ;RB0????ru
    BSF TRISB,2
    BANKSEL ANSELB ;PORTB??
    MOVLW h'00'
    MOVWF ANSELB
;    BANKSEL LATA
;    BANKSEL IOCBP
;    BSF IOCBP,2
    BANKSEL IOCBN
    BSF IOCBN,2
MAINLOOP
    NOP
;    MOVLW 0x02
;    MOVWF COUNT
;    LOOP0
;	BANKSEL TMR0
;	MOVLW B'00001100';256-244 
;	MOVWF TMR0
;	    LOOP1
;		BTFSS  INTCON,2
;		GOTO LOOP1
;    CLRF INTCON
;    DECFSZ COUNT,1
;    GOTO LOOP0
    GOTO MAINLOOP                         ; loop forever
END