org 0x0
  
; PIC16F1786 Configuration Bit Settings

; Assembly source line config statements

#include "p16f1786.inc"

; CONFIG1
; __config 0xFFFF
 __CONFIG _CONFIG1, _FOSC_ECH & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _CLKOUTEN_OFF & _IESO_ON & _FCMEN_ON
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _WRT_OFF & _VCAPEN_OFF & _PLLEN_ON & _STVREN_ON & _BORV_LO & _LPBOR_OFF & _LVP_ON
 
	UDATA_SHR
DELAYVAR1 RES 1H
light_cont RES 1H
 
RES_VECT  CODE    0x0000 
	  PAGESEL MAIN
	  GOTO    INIT 
MAIN_PROG CODE 

INIT:
    BANKSEL ANSELA 
    CLRF ANSELA
    BANKSEL OSCCON
    BCF OSCCON,0 ;????????
    BCF OSCCON,1
    BSF OSCCON,6; ??????????31k HZ
    BCF OSCCON,5;
    BSF OSCCON,4;
    BSF OSCCON,3;
    BANKSEL TRISA
    CLRF TRISA  ;?????,???? ???????
    MOVLW H'00'
    MOVWF TRISA ;????RA0-RA7??????
    BANKSEL LATA ;??????
    CLRF LATA 
    MOVLW H'ff' ;????
    MOVWF LATA
    MOVLW h'0F'
    MOVWF DELAYVAR1
    BANKSEL OPTION_REG
    BCF OPTION_REG,PS0
    BSF OPTION_REG,PS1
    BSF OPTION_REG,PS2
    BCF OPTION_REG,PSA
    BCF OPTION_REG,TMR0CS;??8??????
    BANKSEL INTCON
    BCF INTCON,TMR0IE ;????????
    BANKSEL TMR0
    CLRF TMR0
    GOTO MAIN
    
MAIN:
    nop
    BTFSS INTCON,TMR0IF ;?????????
    GOTO MAIN
    BCF INTCON,TMR0IF ;????0
    DECFSZ DELAYVAR1
    GOTO MAIN
    MOVLW H'0F'
    MOVWF DELAYVAR1
    BANKSEL LATA
    MOVLW H'00'
    MOVWF LATA
    GOTO DELAY
DELAY:
    BTFSS INTCON,TMR0IF ;?????????
    GOTO DELAY
    BCF INTCON,TMR0IF ;????0
    DECFSZ DELAYVAR1
    GOTO DELAY
    MOVLW H'0F'
    MOVWF DELAYVAR1
    BANKSEL LATA
    MOVLW H'FF'
    MOVWF LATA
    GOTO MAIN
end